<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ProductVariant;
use App\Models\PropertyOption;
use Illuminate\Support\Facades\DB;

class ProductVariantPropertyOptionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Пример: для каждого варианта товара указываем slug'и опций
        $variantOptions = [

            // Товар Смартфон Apple iPhone 16 (7 вариантов)
            
            'apple-iphone-16-128gb-white' => [
                'lineup' => 'iphone-16',
                'built_in_memory' => '128gb',
                'ram' => '8gb',
                'screen_size' => '6-1',
                'nfc' => 'yes',
                'case_color' => 'belyy',
                'battery_capacity' => '3561',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-16-128gb-teal' => [
                'lineup' => 'iphone-16',
                'built_in_memory' => '128gb',
                'ram' => '8gb',
                'screen_size' => '6-1',
                'nfc' => 'yes',
                'case_color' => 'biryuzovyy',
                'battery_capacity' => '3561',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-16-128gb-ultramarine' => [
                'lineup' => 'iphone-16',
                'built_in_memory' => '128gb',
                'ram' => '8gb',
                'screen_size' => '6-1',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '3561',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-16-128gb-black' => [
                'lineup' => 'iphone-16',
                'built_in_memory' => '128gb',
                'ram' => '8gb',
                'screen_size' => '6-1',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '3561',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-16-256gb-white' => [
                'lineup' => 'iphone-16',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-1',
                'nfc' => 'yes',
                'case_color' => 'belyy',
                'battery_capacity' => '3561',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-16-256gb-black' => [
                'lineup' => 'iphone-16',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-1',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '3561',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-16-256gb-pink' => [
                'lineup' => 'iphone-16',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-1',
                'nfc' => 'yes',
                'case_color' => 'rozovyy',
                'battery_capacity' => '3561',
                'w_charg_sup' => 'yes',
            ],


            // Товар Смартфон Apple iPhone 17 (6 вариантов)
            
            'apple-iphone-17-256gb-white' => [
                'lineup' => 'iphone-17',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-3',
                'nfc' => 'yes',
                'case_color' => 'belyy',
                'battery_capacity' => '3692',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-17-256gb-mist-blue' => [
                'lineup' => 'iphone-17',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-3',
                'nfc' => 'yes',
                'case_color' => 'goluboy',
                'battery_capacity' => '3692',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-17-256gb-lavender' => [
                'lineup' => 'iphone-17',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-3',
                'nfc' => 'yes',
                'case_color' => 'sirenevyy',
                'battery_capacity' => '3692',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-17-512gb-white' => [
                'lineup' => 'iphone-17',
                'built_in_memory' => '512gb',
                'ram' => '8gb',
                'screen_size' => '6-3',
                'nfc' => 'yes',
                'case_color' => 'belyy',
                'battery_capacity' => '3692',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-17-512gb-lavender' => [
                'lineup' => 'iphone-17',
                'built_in_memory' => '512gb',
                'ram' => '8gb',
                'screen_size' => '6-3',
                'nfc' => 'yes',
                'case_color' => 'sirenevyy',
                'battery_capacity' => '3692',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-17-512gb-sage' => [
                'lineup' => 'iphone-17',
                'built_in_memory' => '512gb',
                'ram' => '8gb',
                'screen_size' => '6-3',
                'nfc' => 'yes',
                'case_color' => 'zelenyy',
                'battery_capacity' => '3692',
                'w_charg_sup' => 'yes',
            ],


            // Товар Смартфон Apple iPhone 17 Pro Max (6 вариантов)

            'apple-iphone-17-pro-max-256gb-deep-blue' => [
                'lineup' => 'iphone-17-pro-max',
                'built_in_memory' => '256gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '5088',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-17-pro-max-256gb-silver' => [
                'lineup' => 'iphone-17-pro-max',
                'built_in_memory' => '256gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'serebristyy',
                'battery_capacity' => '5088',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-17-pro-max-256gb-cosmic-orange' => [
                'lineup' => 'iphone-17-pro-max',
                'built_in_memory' => '256gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'oranzhevyy',
                'battery_capacity' => '5088',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-17-pro-max-512gb-silver' => [
                'lineup' => 'iphone-17-pro-max',
                'built_in_memory' => '512gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'serebristyy',
                'battery_capacity' => '5088',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-17-pro-max-512gb-cosmic-orange' => [
                'lineup' => 'iphone-17-pro-max',
                'built_in_memory' => '512gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'oranzhevyy',
                'battery_capacity' => '5088',
                'w_charg_sup' => 'yes',
            ],
            'apple-iphone-17-pro-max-512gb-deep-blue' => [
                'lineup' => 'iphone-17-pro-max',
                'built_in_memory' => '512gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '5088',
                'w_charg_sup' => 'yes',
            ],


            // Товар Смартфон Samsung Galaxy S25 Ultra (9 вариантов)

            'samsung-galaxy-s25-ultra-12gb256gb-cernyi-titan' => [
                'lineup' => 'samsung-s25-ultra',
                'built_in_memory' => '256gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'yes',
            ],
            'samsung-galaxy-s25-ultra-12gb256gb-serebryanyi-titan' => [
                'lineup' => 'samsung-s25-ultra',
                'built_in_memory' => '256gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'serebristyy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'yes',
            ],
            'samsung-galaxy-s25-ultra-12gb256gb-sinii-titan' => [
                'lineup' => 'samsung-s25-ultra',
                'built_in_memory' => '256gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'yes',
            ],
            'samsung-galaxy-s25-ultra-12gb512gb-cernyi-titan' => [
                'lineup' => 'samsung-s25-ultra',
                'built_in_memory' => '512gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'yes',
            ],
            'samsung-galaxy-s25-ultra-12gb512gb-serebryanyi-titan' => [
                'lineup' => 'samsung-s25-ultra',
                'built_in_memory' => '512gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'serebristyy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'yes',
            ],
            'samsung-galaxy-s25-ultra-12gb512gb-sinii-titan' => [
                'lineup' => 'samsung-s25-ultra',
                'built_in_memory' => '512gb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'yes',
            ],
            'samsung-galaxy-s25-ultra-12gb1tb-seryi-titan' => [
                'lineup' => 'samsung-s25-ultra',
                'built_in_memory' => '1tb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'seryy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'yes',
            ],
            'samsung-galaxy-s25-ultra-12gb1tb-serebryanyi-titan' => [
                'lineup' => 'samsung-s25-ultra',
                'built_in_memory' => '1tb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'serebristyy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'yes',
            ],
            'samsung-galaxy-s25-ultra-12gb1tb-sinii-titan' => [
                'lineup' => 'samsung-s25-ultra',
                'built_in_memory' => '1tb',
                'ram' => '12gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'yes',
            ],


            // Товар Смартфон Samsung Galaxy A57 5G (6 вариантов)

            'samsung-galaxy-a57-5g-8gb128gb-seryi' => [
                'lineup' => 'samsung-a57-5g',
                'built_in_memory' => '128gb',
                'ram' => '8gb',
                'screen_size' => '6-7',
                'nfc' => 'yes',
                'case_color' => 'seryy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'no',
            ],
            'samsung-galaxy-a57-5g-8gb128gb-sinyi' => [
                'lineup' => 'samsung-a57-5g',
                'built_in_memory' => '128gb',
                'ram' => '8gb',
                'screen_size' => '6-7',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'no',
            ],
            'samsung-galaxy-a57-5g-8gb256gb-seryi' => [
                'lineup' => 'samsung-a57-5g',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-7',
                'nfc' => 'yes',
                'case_color' => 'seryy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'no',
            ],
            'samsung-galaxy-a57-5g-8gb256gb-sinyi' => [
                'lineup' => 'samsung-a57-5g',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-7',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'no',
            ],
            'samsung-galaxy-a57-5g-8gb512gb-seryi' => [
                'lineup' => 'samsung-a57-5g',
                'built_in_memory' => '512gb',
                'ram' => '8gb',
                'screen_size' => '6-7',
                'nfc' => 'yes',
                'case_color' => 'seryy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'no',
            ],
            'samsung-galaxy-a57-5g-8gb512gb-sinyi' => [
                'lineup' => 'samsung-a57-5g',
                'built_in_memory' => '512gb',
                'ram' => '8gb',
                'screen_size' => '6-7',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '5000',
                'w_charg_sup' => 'no',
            ],


            // Товар Смартфон Xiaomi Redmi 15C (13 вариантов)

            'xiaomi-redmi-15c-4gb-128gb-midnight-black' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '128gb',
                'ram' => '4gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-4gb-128gb-mint-green' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '128gb',
                'ram' => '4gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'zelenyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-4gb-128gb-moonlight-blue' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '128gb',
                'ram' => '4gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-4gb-128gb-twilight-orange' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '128gb',
                'ram' => '4gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'oranzhevyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-4gb-256gb-midnight-black' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '256gb',
                'ram' => '4gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-4gb-256gb-moonlight-blue' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '256gb',
                'ram' => '4gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-4gb-256gb-mint-green' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '256gb',
                'ram' => '4gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'zelenyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-6gb-128gb-midnight-black' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '128gb',
                'ram' => '6gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-6gb-128gb-mint-green' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '128gb',
                'ram' => '6gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'zelenyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-6gb-128gb-moonlight-blue' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '128gb',
                'ram' => '6gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-8gb-256gb-midnight-black' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-8gb-256gb-moonlight-blue' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-15c-8gb-256gb-mint-green' => [
                'lineup' => 'xiaomi-redmi-15c',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-9',
                'nfc' => 'yes',
                'case_color' => 'zelenyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],


            // Товар Смартфон Xiaomi Redmi Note 14 (8 вариантов)

            'xiaomi-redmi-note-14-6gb-128gb-midnight-black' => [
                'lineup' => 'xiaomi-redmi-note-14',
                'built_in_memory' => '128gb',
                'ram' => '6gb',
                'screen_size' => '6-67',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '5500',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-note-14-6gb-128gb-ocean-blue' => [
                'lineup' => 'xiaomi-redmi-note-14',
                'built_in_memory' => '128gb',
                'ram' => '6gb',
                'screen_size' => '6-67',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '5500',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-note-14-6gb-128gb-lime-green' => [
                'lineup' => 'xiaomi-redmi-note-14',
                'built_in_memory' => '128gb',
                'ram' => '6gb',
                'screen_size' => '6-67',
                'nfc' => 'yes',
                'case_color' => 'zelenyy',
                'battery_capacity' => '5500',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-note-14-8gb-256gb-midnight-black' => [
                'lineup' => 'xiaomi-redmi-note-14',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-67',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '5500',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-note-14-8gb-258-ocean-blue' => [
                'lineup' => 'xiaomi-redmi-note-14',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-67',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '5500',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-note-14-8gb-256gb-lime-green' => [
                'lineup' => 'xiaomi-redmi-note-14',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-67',
                'nfc' => 'yes',
                'case_color' => 'zelenyy',
                'battery_capacity' => '5500',
                'w_charg_sup' => 'no',
            ],


            // Товар Смартфон Xiaomi Redmi Note 15 (8 вариантов)

            'xiaomi-redmi-note-15-6gb-128gb-black' => [
                'lineup' => 'xiaomi-redmi-note-15',
                'built_in_memory' => '128gb',
                'ram' => '6gb',
                'screen_size' => '6-77',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-note-15-6gb-128gb-purple' => [
                'lineup' => 'xiaomi-redmi-note-15',
                'built_in_memory' => '128gb',
                'ram' => '6gb',
                'screen_size' => '6-77',
                'nfc' => 'yes',
                'case_color' => 'fioletovyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-note-15-6gb-128gb-glacier-blue' => [
                'lineup' => 'xiaomi-redmi-note-15',
                'built_in_memory' => '128gb',
                'ram' => '6gb',
                'screen_size' => '6-77',
                'nfc' => 'yes',
                'case_color' => 'siniy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-note-15-8gb-256gb-black' => [
                'lineup' => 'xiaomi-redmi-note-15',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-77',
                'nfc' => 'yes',
                'case_color' => 'chernyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-note-15-8gb-256gb-forest-green' => [
                'lineup' => 'xiaomi-redmi-note-15',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-77',
                'nfc' => 'yes',
                'case_color' => 'zelenyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],
            'xiaomi-redmi-note-15-8gb-256gb-purple' => [
                'lineup' => 'xiaomi-redmi-note-15',
                'built_in_memory' => '256gb',
                'ram' => '8gb',
                'screen_size' => '6-77',
                'nfc' => 'yes',
                'case_color' => 'fioletovyy',
                'battery_capacity' => '6000',
                'w_charg_sup' => 'no',
            ],

        ];

        foreach ($variantOptions as $variantSlug => $options) {
            $variant = ProductVariant::where('slug', $variantSlug)->first();
            if (!$variant) continue;

            foreach ($options as $propertySlug => $optionSlug) {
                $option = PropertyOption::where('slug', $optionSlug)->first();
                if ($option) {
                    DB::table('product_variant_property_options')->updateOrInsert(
                        [
                            'product_variant_id' => $variant->id,
                            'property_option_id' => $option->id,
                        ],
                        [
                            'created_at' => now(),
                            'updated_at' => now(),
                        ]
                    );
                }
            }
        }
    }
}
